#!/usr/bin/env python3
"""
lissajou_gen.py - Generate ca65 .inc files with Lissajous position tables.

Outputs:
  lissajous_pretzel.inc   a=3, b=2, phase=pi/4  (pretzel / 3:2 knot)
  lissajous_inf.inc       a=1, b=2, phase=0      (sideways infinity symbol)
"""
import math

MIN_X    = 24
MAX_X    = 320
MIN_Y    = 50
MAX_Y    = 229
N_POINTS = 256

PATTERNS = [
#    dict(name="pretzel", a=3, b=2, phase=math.pi/4,
#         label="Pretzel (3:2, phase=pi/4)"),
    dict(name="inf",     a=1, b=2, phase=0,
         label="Infinity symbol (1:2, phase=0)"),
]

def generate(a, b, phase):
    cx = (MIN_X + MAX_X) / 2
    cy = (MIN_Y + MAX_Y) / 2
    ax = (MAX_X - MIN_X) / 2
    ay = (MAX_Y - MIN_Y) / 2
    xpoints = []
    ypoints = []
    for i in range(N_POINTS):
        t = 2 * math.pi * i / N_POINTS
        x = round(cx + ax * math.sin(a * t + phase))
        y = round(cy + ay * math.sin(b * t))
        xpoints.append(max(MIN_X, min(MAX_X, x)))
        ypoints.append(max(MIN_Y, min(MAX_Y, y)))
    return xpoints, ypoints

def table(vals, directive, per=16):
    lines = []
    for i in range(0, len(vals), per):
        chunk = vals[i:i+per]
        lines.append(f"    {directive} {', '.join(str(v) for v in chunk)}")
    return '\n'.join(lines)

def write_inc(pat, xpoints, ypoints):
    fname = f"lissajous_{pat['name']}.inc"
    hi_bytes = set(v >> 8 for v in xpoints)
    with open(fname, 'w') as f:
        f.write(f"; {fname}\n")
        f.write(f"; {pat['label']}\n")
        f.write(f"; X:[{MIN_X}..{MAX_X}]  Y:[{MIN_Y}..{MAX_Y}]  N={N_POINTS}\n")
        f.write(f"; xpoints_hi values used: {sorted(hi_bytes)}"
                f"  (carry trick for 9th X bit works)\n")
        f.write(f"; Generated by lissajou_gen.py - do not edit by hand\n")
        f.write(f"\n")
        f.write(f"N_POINTS = {N_POINTS}\n")
        f.write(f"\n")
        f.write(f"ypoints:\n{table(ypoints, '.byte')}\n")
        f.write(f"\n")
        f.write(f"xpoints_lo:\n{table(xpoints, '.lobytes')}\n")
        f.write(f"\n")
        f.write(f"xpoints_hi:\n{table(xpoints, '.hibytes')}\n")
    print(f"wrote {fname}  ({N_POINTS} points, X {min(xpoints)}..{max(xpoints)}, Y {min(ypoints)}..{max(ypoints)})")

for pat in PATTERNS:
    xp, yp = generate(pat['a'], pat['b'], pat['phase'])
    write_inc(pat, xp, yp)

print("done.")
